const express=require('express')
const router=express.Router()
const {protect}=require('../middleware/authMiddleware')
const  {postANeed}  = require('../controllers/donationManagement/postANeed')
const {getAllNeeds}=require('../controllers/donationManagement/getAllNeeds')
const {getNeedById}=require('../controllers/donationManagement/getNeedById')
const {getNeedsByNGO}=require('../controllers/donationManagement/getNeedsByNGO')
router.post('/postANeed',protect,postANeed)
router.get('/getAllNeeds',getAllNeeds)
router.get('/getNeedById/:id',getNeedById)
router.get('/getNeedsByNGO',getNeedsByNGO)
module.exports=router