const express=require('express')
const router=express.Router()
const routeProtect=require('../middleware/authMiddleware')
const needController=require('../controllers/donationManagement/needController')
const paymentController=require('../controllers/donationManagement/paymentController')
const donateItems=require('../controllers/donationManagement/donateItems')
console.log(typeof routeProtect.protect)
router.post("/initiatePayment",routeProtect.protect,paymentController.initiatePayment);
router.get('/verifyPayment',paymentController.verifyPayment)
router.post('/postANeed',routeProtect.protect,needController.postANeed)
router.get('/getAllNeeds',needController.getAllNeeds)
router.get('/getNeedsByNGO',needController.getNeedsByNGO)
router.get('/getNeedsById',needController.getNeedById)
router.post('/donateItems',routeProtect.protect,donateItems)
module.exports=router